### ISSUE TITLE
Any way to fetch other translations?

### ISSUE THREAD

**Issue by adam-rocska** [flix-tech/stencil-i18n#6]
Is there any way by design to fetch alternative / explicit localizations?

For example:
Let's assume my localization function's "phantom definition" is:
```
export function _(key: MessageKey, _params?: { [index: string]: string | number }): string {
  return key;
}
```

if there any way to do something like: `_("some.key", {}, "de_DE")`?

**Comment by hinterdupfinger** [comment]
Within one build only one language is possible at the moment, as the implementation currently just loads one translation JSON per build.

**Comment by adam-rocska** [comment]
@hinterdupfinger Got it.

Would you accept a contribution from one of my staff members to extend the functionality maybe?

**Comment by hinterdupfinger** [comment]
Sure, I would be happy to review your pull request 👍
